all:
	g++ -std=c++11 -o window.exe hello_framebuffer.cpp /media/theengineer/Main2/openGL_practice/src/Shader.cpp\
	 	/media/theengineer/Main2/openGL_practice/src/stb_image.cpp \
		/media/theengineer/Main2/openGL_practice/src/CustomizedModelLoading/Mesh.cpp \
	 	/media/theengineer/Main2/openGL_practice/src/CustomizedModelLoading/Texture.cpp \
	 	/media/theengineer/Main2/openGL_practice/src/CustomizedModelLoading/Model.cpp \
		-I/media/theengineer/Main2/openGL_practice/include -lglfw3 -lGL -lGLU -lX11 -lpthread -lXrandr -lXi -lglad -ldl -ldatstringutils -lassimp
